export const properties = [
  {
    "id": 1,
    "name": "Hinjewadi Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Hinjewadi Residency A",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Hinjewadi",
    "builtUpArea": "1053 sqft",
    "expectedPrice": 9342802,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 2,
    "availableAmenities": [
      "Garden",
      "Play Area",
      "Gym"
    ],
    "latitude": 18.472194,
    "longitude": 73.83361
  },
  {
    "id": 2,
    "name": "Hinjewadi Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Hinjewadi Residency B",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Hinjewadi",
    "builtUpArea": "1320 sqft",
    "expectedPrice": 15337,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 2,
    "availableAmenities": [
      "Parking",
      "Gym",
      "Garden"
    ],
    "latitude": 18.569994,
    "longitude": 73.918892
  },
  {
    "id": 3,
    "name": "Wakad Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Wakad Residency A",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Wakad",
    "builtUpArea": "997 sqft",
    "expectedPrice": 10811792,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 2,
    "availableAmenities": [
      "Gym",
      "Garden",
      "Security"
    ],
    "latitude": 18.543959,
    "longitude": 73.807412
  },
  {
    "id": 4,
    "name": "Wakad Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Wakad Residency B",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Wakad",
    "builtUpArea": "804 sqft",
    "expectedPrice": 25524,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 2,
    "availableAmenities": [
      "Garden",
      "Lift",
      "Parking"
    ],
    "latitude": 18.501799,
    "longitude": 73.784012
  },
  {
    "id": 5,
    "name": "Baner Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Baner Residency A",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Baner",
    "builtUpArea": "1388 sqft",
    "expectedPrice": 11968163,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 2,
    "availableAmenities": [
      "Garden",
      "Club House",
      "Parking"
    ],
    "latitude": 18.488347,
    "longitude": 73.931179
  },
  {
    "id": 6,
    "name": "Baner Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Baner Residency B",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Baner",
    "builtUpArea": "1340 sqft",
    "expectedPrice": 22971,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 1,
    "availableAmenities": [
      "Club House",
      "Security",
      "Lift"
    ],
    "latitude": 18.541178,
    "longitude": 73.825108
  },
  {
    "id": 7,
    "name": "Balewadi Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Balewadi Residency A",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Balewadi",
    "builtUpArea": "1213 sqft",
    "expectedPrice": 10004849,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 0,
    "availableAmenities": [
      "Security",
      "Club House",
      "Gym"
    ],
    "latitude": 18.527421,
    "longitude": 73.865768
  },
  {
    "id": 8,
    "name": "Balewadi Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Balewadi Residency B",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Balewadi",
    "builtUpArea": "1237 sqft",
    "expectedPrice": 28517,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 2,
    "availableAmenities": [
      "Lift",
      "Garden",
      "Gym"
    ],
    "latitude": 18.516851,
    "longitude": 73.835879
  },
  {
    "id": 9,
    "name": "Aundh Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Aundh Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Aundh",
    "builtUpArea": "1070 sqft",
    "expectedPrice": 9661559,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 1,
    "availableAmenities": [
      "Security",
      "Parking",
      "Gym"
    ],
    "latitude": 18.466077,
    "longitude": 73.917298
  },
  {
    "id": 10,
    "name": "Aundh Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Aundh Residency B",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Aundh",
    "builtUpArea": "914 sqft",
    "expectedPrice": 27793,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 0,
    "availableAmenities": [
      "Security",
      "Garden",
      "Lift"
    ],
    "latitude": 18.476025,
    "longitude": 73.872774
  },
  {
    "id": 11,
    "name": "Bavdhan Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Bavdhan Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Bavdhan",
    "builtUpArea": "1106 sqft",
    "expectedPrice": 13525638,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 0,
    "availableAmenities": [
      "Club House",
      "Gym",
      "Security"
    ],
    "latitude": 18.575532,
    "longitude": 73.877754
  },
  {
    "id": 12,
    "name": "Bavdhan Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Bavdhan Residency B",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Bavdhan",
    "builtUpArea": "762 sqft",
    "expectedPrice": 21049,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 1,
    "availableAmenities": [
      "Play Area",
      "Gym",
      "Security"
    ],
    "latitude": 18.552121,
    "longitude": 73.786205
  },
  {
    "id": 13,
    "name": "Pashan Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Pashan Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Pashan",
    "builtUpArea": "1372 sqft",
    "expectedPrice": 14473206,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 1,
    "availableAmenities": [
      "Club House",
      "Gym",
      "Garden"
    ],
    "latitude": 18.494786,
    "longitude": 73.783527
  },
  {
    "id": 14,
    "name": "Pashan Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Pashan Residency B",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Pashan",
    "builtUpArea": "719 sqft",
    "expectedPrice": 27291,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 1,
    "availableAmenities": [
      "Play Area",
      "Security",
      "Garden"
    ],
    "latitude": 18.484697,
    "longitude": 73.892165
  },
  {
    "id": 15,
    "name": "Sus Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Sus Residency A",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Sus",
    "builtUpArea": "1032 sqft",
    "expectedPrice": 7722240,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 1,
    "availableAmenities": [
      "Parking",
      "Garden",
      "Club House"
    ],
    "latitude": 18.451938,
    "longitude": 73.787457
  },
  {
    "id": 16,
    "name": "Sus Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Sus Residency B",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Sus",
    "builtUpArea": "847 sqft",
    "expectedPrice": 20177,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 1,
    "availableAmenities": [
      "Garden",
      "Play Area",
      "Gym"
    ],
    "latitude": 18.57328,
    "longitude": 73.802214
  },
  {
    "id": 17,
    "name": "Mahalunge Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Mahalunge Residency A",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Mahalunge",
    "builtUpArea": "751 sqft",
    "expectedPrice": 14244390,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 0,
    "availableAmenities": [
      "Lift",
      "Garden",
      "Parking"
    ],
    "latitude": 18.51346,
    "longitude": 73.807253
  },
  {
    "id": 18,
    "name": "Mahalunge Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Mahalunge Residency B",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Mahalunge",
    "builtUpArea": "1189 sqft",
    "expectedPrice": 29759,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 2,
    "availableAmenities": [
      "Security",
      "Lift",
      "Play Area"
    ],
    "latitude": 18.525049,
    "longitude": 73.87279
  },
  {
    "id": 19,
    "name": "Pimple Nilakh Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Pimple Nilakh Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Pimple Nilakh",
    "builtUpArea": "1188 sqft",
    "expectedPrice": 8188491,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 0,
    "availableAmenities": [
      "Gym",
      "Security",
      "Parking"
    ],
    "latitude": 18.46223,
    "longitude": 73.804726
  },
  {
    "id": 20,
    "name": "Pimple Nilakh Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Pimple Nilakh Residency B",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Pimple Nilakh",
    "builtUpArea": "1003 sqft",
    "expectedPrice": 28623,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 2,
    "availableAmenities": [
      "Parking",
      "Security",
      "Garden"
    ],
    "latitude": 18.594744,
    "longitude": 73.785768
  },
  {
    "id": 21,
    "name": "Pimple Saudagar Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Pimple Saudagar Residency A",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Pimple Saudagar",
    "builtUpArea": "1139 sqft",
    "expectedPrice": 9089891,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 2,
    "availableAmenities": [
      "Lift",
      "Play Area",
      "Gym"
    ],
    "latitude": 18.56495,
    "longitude": 73.821323
  },
  {
    "id": 22,
    "name": "Pimple Saudagar Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Pimple Saudagar Residency B",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Pimple Saudagar",
    "builtUpArea": "1302 sqft",
    "expectedPrice": 23768,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 0,
    "availableAmenities": [
      "Security",
      "Parking",
      "Play Area"
    ],
    "latitude": 18.477555,
    "longitude": 73.862185
  },
  {
    "id": 23,
    "name": "Kharadi Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Kharadi Residency A",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Kharadi",
    "builtUpArea": "985 sqft",
    "expectedPrice": 12497594,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 1,
    "availableAmenities": [
      "Play Area",
      "Parking",
      "Club House"
    ],
    "latitude": 18.507308,
    "longitude": 73.796147
  },
  {
    "id": 24,
    "name": "Kharadi Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Kharadi Residency B",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Kharadi",
    "builtUpArea": "1233 sqft",
    "expectedPrice": 22607,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 2,
    "availableAmenities": [
      "Lift",
      "Parking",
      "Gym"
    ],
    "latitude": 18.590439,
    "longitude": 73.845014
  },
  {
    "id": 25,
    "name": "Hadapsar Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Hadapsar Residency A",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Hadapsar",
    "builtUpArea": "1012 sqft",
    "expectedPrice": 7709117,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 0,
    "availableAmenities": [
      "Garden",
      "Security",
      "Club House"
    ],
    "latitude": 18.501257,
    "longitude": 73.808002
  },
  {
    "id": 26,
    "name": "Hadapsar Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Hadapsar Residency B",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Hadapsar",
    "builtUpArea": "741 sqft",
    "expectedPrice": 15657,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 0,
    "availableAmenities": [
      "Security",
      "Parking",
      "Play Area"
    ],
    "latitude": 18.595187,
    "longitude": 73.803625
  },
  {
    "id": 27,
    "name": "Undri Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Undri Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Undri",
    "builtUpArea": "1034 sqft",
    "expectedPrice": 13620008,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 0,
    "availableAmenities": [
      "Security",
      "Lift",
      "Gym"
    ],
    "latitude": 18.560684,
    "longitude": 73.859857
  },
  {
    "id": 28,
    "name": "Undri Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Undri Residency B",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Undri",
    "builtUpArea": "1293 sqft",
    "expectedPrice": 24542,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 2,
    "availableAmenities": [
      "Parking",
      "Club House",
      "Lift"
    ],
    "latitude": 18.531903,
    "longitude": 73.868178
  },
  {
    "id": 29,
    "name": "Pisoli Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Pisoli Residency A",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Pisoli",
    "builtUpArea": "801 sqft",
    "expectedPrice": 10050022,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 1,
    "availableAmenities": [
      "Club House",
      "Garden",
      "Gym"
    ],
    "latitude": 18.498523,
    "longitude": 73.827055
  },
  {
    "id": 30,
    "name": "Pisoli Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Pisoli Residency B",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Pisoli",
    "builtUpArea": "1342 sqft",
    "expectedPrice": 23424,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 0,
    "availableAmenities": [
      "Security",
      "Club House",
      "Gym"
    ],
    "latitude": 18.543356,
    "longitude": 73.799862
  },
  {
    "id": 31,
    "name": "Kondhwa Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Kondhwa Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Kondhwa",
    "builtUpArea": "1021 sqft",
    "expectedPrice": 11426519,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 0,
    "availableAmenities": [
      "Gym",
      "Parking",
      "Security"
    ],
    "latitude": 18.572111,
    "longitude": 73.92647
  },
  {
    "id": 32,
    "name": "Kondhwa Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Kondhwa Residency B",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Kondhwa",
    "builtUpArea": "1298 sqft",
    "expectedPrice": 23482,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 2,
    "availableAmenities": [
      "Gym",
      "Play Area",
      "Parking"
    ],
    "latitude": 18.477106,
    "longitude": 73.80381
  },
  {
    "id": 33,
    "name": "Mohammadwadi Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Mohammadwadi Residency A",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Mohammadwadi",
    "builtUpArea": "936 sqft",
    "expectedPrice": 9038589,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 0,
    "availableAmenities": [
      "Play Area",
      "Parking",
      "Garden"
    ],
    "latitude": 18.572083,
    "longitude": 73.79221
  },
  {
    "id": 34,
    "name": "Mohammadwadi Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Mohammadwadi Residency B",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Mohammadwadi",
    "builtUpArea": "815 sqft",
    "expectedPrice": 21224,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 1,
    "availableAmenities": [
      "Security",
      "Play Area",
      "Club House"
    ],
    "latitude": 18.566086,
    "longitude": 73.907618
  },
  {
    "id": 35,
    "name": "Wanowrie Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Wanowrie Residency A",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Wanowrie",
    "builtUpArea": "1302 sqft",
    "expectedPrice": 7594639,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 1,
    "availableAmenities": [
      "Play Area",
      "Garden",
      "Parking"
    ],
    "latitude": 18.534391,
    "longitude": 73.783051
  },
  {
    "id": 36,
    "name": "Wanowrie Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Wanowrie Residency B",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Wanowrie",
    "builtUpArea": "738 sqft",
    "expectedPrice": 25080,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 0,
    "availableAmenities": [
      "Garden",
      "Club House",
      "Gym"
    ],
    "latitude": 18.479105,
    "longitude": 73.926653
  },
  {
    "id": 37,
    "name": "Fatima Nagar Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Fatima Nagar Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Fatima Nagar",
    "builtUpArea": "839 sqft",
    "expectedPrice": 9376499,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 0,
    "availableAmenities": [
      "Play Area",
      "Lift",
      "Security"
    ],
    "latitude": 18.557646,
    "longitude": 73.893689
  },
  {
    "id": 38,
    "name": "Fatima Nagar Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Fatima Nagar Residency B",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Fatima Nagar",
    "builtUpArea": "1148 sqft",
    "expectedPrice": 26933,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 0,
    "availableAmenities": [
      "Play Area",
      "Parking",
      "Gym"
    ],
    "latitude": 18.481438,
    "longitude": 73.788371
  },
  {
    "id": 39,
    "name": "Handewadi Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Handewadi Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Handewadi",
    "builtUpArea": "1231 sqft",
    "expectedPrice": 9444778,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 1,
    "availableAmenities": [
      "Lift",
      "Parking",
      "Gym"
    ],
    "latitude": 18.489779,
    "longitude": 73.810817
  },
  {
    "id": 40,
    "name": "Handewadi Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Handewadi Residency B",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Handewadi",
    "builtUpArea": "1302 sqft",
    "expectedPrice": 20495,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 2,
    "availableAmenities": [
      "Garden",
      "Security",
      "Play Area"
    ],
    "latitude": 18.477314,
    "longitude": 73.927507
  },
  {
    "id": 41,
    "name": "Manjri Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Manjri Residency A",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Manjri",
    "builtUpArea": "960 sqft",
    "expectedPrice": 8358099,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 1,
    "availableAmenities": [
      "Lift",
      "Club House",
      "Security"
    ],
    "latitude": 18.493324,
    "longitude": 73.881596
  },
  {
    "id": 42,
    "name": "Manjri Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Manjri Residency B",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Manjri",
    "builtUpArea": "1297 sqft",
    "expectedPrice": 28377,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 1,
    "availableAmenities": [
      "Club House",
      "Parking",
      "Gym"
    ],
    "latitude": 18.445142,
    "longitude": 73.842387
  },
  {
    "id": 43,
    "name": "Viman Nagar Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Viman Nagar Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Viman Nagar",
    "builtUpArea": "1220 sqft",
    "expectedPrice": 8099389,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 2,
    "availableAmenities": [
      "Play Area",
      "Parking",
      "Lift"
    ],
    "latitude": 18.483209,
    "longitude": 73.900798
  },
  {
    "id": 44,
    "name": "Viman Nagar Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Viman Nagar Residency B",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Viman Nagar",
    "builtUpArea": "1270 sqft",
    "expectedPrice": 18755,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 0,
    "availableAmenities": [
      "Parking",
      "Security",
      "Club House"
    ],
    "latitude": 18.514435,
    "longitude": 73.850098
  },
  {
    "id": 45,
    "name": "Kalyani Nagar Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Kalyani Nagar Residency A",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Kalyani Nagar",
    "builtUpArea": "808 sqft",
    "expectedPrice": 14013624,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 2,
    "availableAmenities": [
      "Parking",
      "Security",
      "Garden"
    ],
    "latitude": 18.535477,
    "longitude": 73.868177
  },
  {
    "id": 46,
    "name": "Kalyani Nagar Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Kalyani Nagar Residency B",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Kalyani Nagar",
    "builtUpArea": "763 sqft",
    "expectedPrice": 24180,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 2,
    "availableAmenities": [
      "Play Area",
      "Gym",
      "Garden"
    ],
    "latitude": 18.512409,
    "longitude": 73.904503
  },
  {
    "id": 47,
    "name": "Yerwada Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Yerwada Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Yerwada",
    "builtUpArea": "1286 sqft",
    "expectedPrice": 10943622,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 2,
    "availableAmenities": [
      "Parking",
      "Lift",
      "Garden"
    ],
    "latitude": 18.585358,
    "longitude": 73.833184
  },
  {
    "id": 48,
    "name": "Yerwada Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Yerwada Residency B",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Yerwada",
    "builtUpArea": "1341 sqft",
    "expectedPrice": 15228,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 0,
    "availableAmenities": [
      "Lift",
      "Play Area",
      "Club House"
    ],
    "latitude": 18.56098,
    "longitude": 73.791229
  },
  {
    "id": 49,
    "name": "Mundhwa Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Mundhwa Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Mundhwa",
    "builtUpArea": "1195 sqft",
    "expectedPrice": 7434410,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 0,
    "availableAmenities": [
      "Parking",
      "Lift",
      "Security"
    ],
    "latitude": 18.566222,
    "longitude": 73.926993
  },
  {
    "id": 50,
    "name": "Mundhwa Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Mundhwa Residency B",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Mundhwa",
    "builtUpArea": "733 sqft",
    "expectedPrice": 18988,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 0,
    "availableAmenities": [
      "Gym",
      "Garden",
      "Lift"
    ],
    "latitude": 18.535382,
    "longitude": 73.807113
  },
  {
    "id": 51,
    "name": "Chandan Nagar Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Chandan Nagar Residency A",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Chandan Nagar",
    "builtUpArea": "799 sqft",
    "expectedPrice": 9684797,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 1,
    "availableAmenities": [
      "Play Area",
      "Lift",
      "Parking"
    ],
    "latitude": 18.493893,
    "longitude": 73.793882
  },
  {
    "id": 52,
    "name": "Chandan Nagar Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Chandan Nagar Residency B",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Chandan Nagar",
    "builtUpArea": "1261 sqft",
    "expectedPrice": 26803,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 2,
    "availableAmenities": [
      "Lift",
      "Parking",
      "Security"
    ],
    "latitude": 18.5735,
    "longitude": 73.908204
  },
  {
    "id": 53,
    "name": "Wagholi Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Wagholi Residency A",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Wagholi",
    "builtUpArea": "1062 sqft",
    "expectedPrice": 10343369,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 2,
    "availableAmenities": [
      "Club House",
      "Parking",
      "Security"
    ],
    "latitude": 18.490624,
    "longitude": 73.826516
  },
  {
    "id": 54,
    "name": "Wagholi Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Wagholi Residency B",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Wagholi",
    "builtUpArea": "948 sqft",
    "expectedPrice": 21385,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 2,
    "availableAmenities": [
      "Security",
      "Play Area",
      "Garden"
    ],
    "latitude": 18.443494,
    "longitude": 73.895597
  },
  {
    "id": 55,
    "name": "Lohegaon Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Lohegaon Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Lohegaon",
    "builtUpArea": "1391 sqft",
    "expectedPrice": 9737477,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 0,
    "availableAmenities": [
      "Gym",
      "Parking",
      "Garden"
    ],
    "latitude": 18.557929,
    "longitude": 73.899038
  },
  {
    "id": 56,
    "name": "Lohegaon Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Lohegaon Residency B",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Lohegaon",
    "builtUpArea": "1302 sqft",
    "expectedPrice": 25397,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 2,
    "availableAmenities": [
      "Lift",
      "Club House",
      "Gym"
    ],
    "latitude": 18.495436,
    "longitude": 73.781422
  },
  {
    "id": 57,
    "name": "Keshav Nagar Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Keshav Nagar Residency A",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Keshav Nagar",
    "builtUpArea": "1050 sqft",
    "expectedPrice": 9199088,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 2,
    "availableAmenities": [
      "Security",
      "Lift",
      "Garden"
    ],
    "latitude": 18.592762,
    "longitude": 73.911445
  },
  {
    "id": 58,
    "name": "Keshav Nagar Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Keshav Nagar Residency B",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Keshav Nagar",
    "builtUpArea": "1347 sqft",
    "expectedPrice": 24792,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 0,
    "availableAmenities": [
      "Gym",
      "Security",
      "Parking"
    ],
    "latitude": 18.447265,
    "longitude": 73.836761
  },
  {
    "id": 59,
    "name": "Ravet Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Ravet Residency A",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Ravet",
    "builtUpArea": "994 sqft",
    "expectedPrice": 13522071,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 1,
    "availableAmenities": [
      "Lift",
      "Security",
      "Parking"
    ],
    "latitude": 18.451785,
    "longitude": 73.868752
  },
  {
    "id": 60,
    "name": "Ravet Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Ravet Residency B",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Ravet",
    "builtUpArea": "1348 sqft",
    "expectedPrice": 23779,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 0,
    "availableAmenities": [
      "Security",
      "Gym",
      "Lift"
    ],
    "latitude": 18.527134,
    "longitude": 73.893767
  },
  {
    "id": 61,
    "name": "Punawale Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Punawale Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Punawale",
    "builtUpArea": "840 sqft",
    "expectedPrice": 8043350,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 0,
    "availableAmenities": [
      "Gym",
      "Lift",
      "Security"
    ],
    "latitude": 18.492776,
    "longitude": 73.922149
  },
  {
    "id": 62,
    "name": "Punawale Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Punawale Residency B",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Punawale",
    "builtUpArea": "702 sqft",
    "expectedPrice": 16117,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 0,
    "availableAmenities": [
      "Parking",
      "Club House",
      "Lift"
    ],
    "latitude": 18.578544,
    "longitude": 73.902752
  },
  {
    "id": 63,
    "name": "Tathawade Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Tathawade Residency A",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Tathawade",
    "builtUpArea": "1050 sqft",
    "expectedPrice": 12393699,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 2,
    "availableAmenities": [
      "Club House",
      "Security",
      "Lift"
    ],
    "latitude": 18.591844,
    "longitude": 73.925354
  },
  {
    "id": 64,
    "name": "Tathawade Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Tathawade Residency B",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Tathawade",
    "builtUpArea": "1364 sqft",
    "expectedPrice": 29739,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 1,
    "availableAmenities": [
      "Club House",
      "Lift",
      "Gym"
    ],
    "latitude": 18.470055,
    "longitude": 73.791829
  },
  {
    "id": 65,
    "name": "Thergaon Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Thergaon Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Thergaon",
    "builtUpArea": "735 sqft",
    "expectedPrice": 11122533,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 2,
    "availableAmenities": [
      "Security",
      "Gym",
      "Parking"
    ],
    "latitude": 18.451711,
    "longitude": 73.912524
  },
  {
    "id": 66,
    "name": "Thergaon Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Thergaon Residency B",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Thergaon",
    "builtUpArea": "848 sqft",
    "expectedPrice": 19224,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 0,
    "availableAmenities": [
      "Play Area",
      "Lift",
      "Gym"
    ],
    "latitude": 18.546372,
    "longitude": 73.793179
  },
  {
    "id": 67,
    "name": "Dange Chowk Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Dange Chowk Residency A",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Dange Chowk",
    "builtUpArea": "1257 sqft",
    "expectedPrice": 13312626,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 0,
    "availableAmenities": [
      "Gym",
      "Security",
      "Club House"
    ],
    "latitude": 18.468567,
    "longitude": 73.913139
  },
  {
    "id": 68,
    "name": "Dange Chowk Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Dange Chowk Residency B",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Dange Chowk",
    "builtUpArea": "1013 sqft",
    "expectedPrice": 24697,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 1,
    "availableAmenities": [
      "Garden",
      "Lift",
      "Play Area"
    ],
    "latitude": 18.528519,
    "longitude": 73.866644
  },
  {
    "id": 69,
    "name": "Nigdi Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Nigdi Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Nigdi",
    "builtUpArea": "1092 sqft",
    "expectedPrice": 9174435,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 2,
    "availableAmenities": [
      "Lift",
      "Gym",
      "Garden"
    ],
    "latitude": 18.494489,
    "longitude": 73.781771
  },
  {
    "id": 70,
    "name": "Nigdi Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Nigdi Residency B",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Nigdi",
    "builtUpArea": "889 sqft",
    "expectedPrice": 28462,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 0,
    "availableAmenities": [
      "Gym",
      "Parking",
      "Security"
    ],
    "latitude": 18.507194,
    "longitude": 73.891252
  },
  {
    "id": 71,
    "name": "Akurdi Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Akurdi Residency A",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Akurdi",
    "builtUpArea": "1039 sqft",
    "expectedPrice": 14476107,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 2,
    "availableAmenities": [
      "Lift",
      "Club House",
      "Parking"
    ],
    "latitude": 18.550217,
    "longitude": 73.786979
  },
  {
    "id": 72,
    "name": "Akurdi Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Akurdi Residency B",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Akurdi",
    "builtUpArea": "1178 sqft",
    "expectedPrice": 18896,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 2,
    "availableAmenities": [
      "Lift",
      "Parking",
      "Club House"
    ],
    "latitude": 18.539199,
    "longitude": 73.796319
  },
  {
    "id": 73,
    "name": "Chinchwad Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Chinchwad Residency A",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Chinchwad",
    "builtUpArea": "804 sqft",
    "expectedPrice": 12058811,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 0,
    "availableAmenities": [
      "Lift",
      "Security",
      "Parking"
    ],
    "latitude": 18.464636,
    "longitude": 73.875255
  },
  {
    "id": 74,
    "name": "Chinchwad Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Chinchwad Residency B",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Chinchwad",
    "builtUpArea": "861 sqft",
    "expectedPrice": 22952,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 0,
    "availableAmenities": [
      "Club House",
      "Gym",
      "Garden"
    ],
    "latitude": 18.545631,
    "longitude": 73.780001
  },
  {
    "id": 75,
    "name": "Pimpri Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Pimpri Residency A",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Pimpri",
    "builtUpArea": "1270 sqft",
    "expectedPrice": 9807859,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 2,
    "availableAmenities": [
      "Play Area",
      "Club House",
      "Gym"
    ],
    "latitude": 18.56389,
    "longitude": 73.917399
  },
  {
    "id": 76,
    "name": "Pimpri Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Pimpri Residency B",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Pimpri",
    "builtUpArea": "1058 sqft",
    "expectedPrice": 20032,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 0,
    "availableAmenities": [
      "Security",
      "Club House",
      "Play Area"
    ],
    "latitude": 18.597061,
    "longitude": 73.92155
  },
  {
    "id": 77,
    "name": "Deccan Gymkhana Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Deccan Gymkhana Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Deccan Gymkhana",
    "builtUpArea": "1011 sqft",
    "expectedPrice": 11938942,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 1,
    "availableAmenities": [
      "Club House",
      "Garden",
      "Gym"
    ],
    "latitude": 18.456696,
    "longitude": 73.923686
  },
  {
    "id": 78,
    "name": "Deccan Gymkhana Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Deccan Gymkhana Residency B",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Deccan Gymkhana",
    "builtUpArea": "833 sqft",
    "expectedPrice": 23478,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 1,
    "availableAmenities": [
      "Club House",
      "Play Area",
      "Lift"
    ],
    "latitude": 18.48167,
    "longitude": 73.932512
  },
  {
    "id": 79,
    "name": "Shivaji Nagar Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Shivaji Nagar Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Shivaji Nagar",
    "builtUpArea": "967 sqft",
    "expectedPrice": 13899904,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 2,
    "availableAmenities": [
      "Parking",
      "Garden",
      "Lift"
    ],
    "latitude": 18.440434,
    "longitude": 73.832832
  },
  {
    "id": 80,
    "name": "Shivaji Nagar Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Shivaji Nagar Residency B",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Shivaji Nagar",
    "builtUpArea": "1359 sqft",
    "expectedPrice": 20151,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 1,
    "availableAmenities": [
      "Security",
      "Garden",
      "Parking"
    ],
    "latitude": 18.528124,
    "longitude": 73.86239
  },
  {
    "id": 81,
    "name": "Erandwane Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Erandwane Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Erandwane",
    "builtUpArea": "1223 sqft",
    "expectedPrice": 11456437,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 1,
    "availableAmenities": [
      "Lift",
      "Gym",
      "Garden"
    ],
    "latitude": 18.441609,
    "longitude": 73.791373
  },
  {
    "id": 82,
    "name": "Erandwane Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Erandwane Residency B",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Erandwane",
    "builtUpArea": "1052 sqft",
    "expectedPrice": 17876,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 0,
    "availableAmenities": [
      "Lift",
      "Club House",
      "Gym"
    ],
    "latitude": 18.486244,
    "longitude": 73.840312
  },
  {
    "id": 83,
    "name": "Model Colony Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Model Colony Residency A",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Model Colony",
    "builtUpArea": "1166 sqft",
    "expectedPrice": 14729724,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 2,
    "availableAmenities": [
      "Parking",
      "Club House",
      "Play Area"
    ],
    "latitude": 18.538664,
    "longitude": 73.911776
  },
  {
    "id": 84,
    "name": "Model Colony Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Model Colony Residency B",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Model Colony",
    "builtUpArea": "738 sqft",
    "expectedPrice": 21079,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 0,
    "availableAmenities": [
      "Parking",
      "Garden",
      "Play Area"
    ],
    "latitude": 18.441261,
    "longitude": 73.918846
  },
  {
    "id": 85,
    "name": "Koregaon Park Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Koregaon Park Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Koregaon Park",
    "builtUpArea": "1244 sqft",
    "expectedPrice": 11805830,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 0,
    "availableAmenities": [
      "Garden",
      "Parking",
      "Gym"
    ],
    "latitude": 18.520324,
    "longitude": 73.78378
  },
  {
    "id": 86,
    "name": "Koregaon Park Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Koregaon Park Residency B",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Koregaon Park",
    "builtUpArea": "1343 sqft",
    "expectedPrice": 25680,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 1,
    "availableAmenities": [
      "Lift",
      "Gym",
      "Security"
    ],
    "latitude": 18.581625,
    "longitude": 73.885163
  },
  {
    "id": 87,
    "name": "Camp Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Camp Residency A",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Camp",
    "builtUpArea": "816 sqft",
    "expectedPrice": 13685839,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 0,
    "availableAmenities": [
      "Play Area",
      "Security",
      "Parking"
    ],
    "latitude": 18.526943,
    "longitude": 73.914648
  },
  {
    "id": 88,
    "name": "Camp Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Camp Residency B",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Camp",
    "builtUpArea": "877 sqft",
    "expectedPrice": 21046,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 2,
    "availableAmenities": [
      "Parking",
      "Club House",
      "Security"
    ],
    "latitude": 18.564831,
    "longitude": 73.930267
  },
  {
    "id": 89,
    "name": "Bund Garden Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Bund Garden Residency A",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Bund Garden",
    "builtUpArea": "1106 sqft",
    "expectedPrice": 14420263,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 2,
    "availableAmenities": [
      "Garden",
      "Club House",
      "Lift"
    ],
    "latitude": 18.51849,
    "longitude": 73.851952
  },
  {
    "id": 90,
    "name": "Bund Garden Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Bund Garden Residency B",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Bund Garden",
    "builtUpArea": "1264 sqft",
    "expectedPrice": 29679,
    "availableFrom": "2025-11-01",
    "bathroom": 1,
    "balcony": 0,
    "availableAmenities": [
      "Garden",
      "Parking",
      "Lift"
    ],
    "latitude": 18.460097,
    "longitude": 73.921118
  },
  {
    "id": 91,
    "name": "MG Road Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "MG Road Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "MG Road",
    "builtUpArea": "1056 sqft",
    "expectedPrice": 14421804,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 1,
    "availableAmenities": [
      "Garden",
      "Play Area",
      "Security"
    ],
    "latitude": 18.566766,
    "longitude": 73.847881
  },
  {
    "id": 92,
    "name": "MG Road Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "MG Road Residency B",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "MG Road",
    "builtUpArea": "1024 sqft",
    "expectedPrice": 20527,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 2,
    "availableAmenities": [
      "Gym",
      "Parking",
      "Garden"
    ],
    "latitude": 18.53479,
    "longitude": 73.849225
  },
  {
    "id": 93,
    "name": "Sadashiv Peth Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Sadashiv Peth Residency A",
    "bhkType": "2 BHK",
    "city": "Pune",
    "locality": "Sadashiv Peth",
    "builtUpArea": "1266 sqft",
    "expectedPrice": 11659903,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 2,
    "availableAmenities": [
      "Club House",
      "Play Area",
      "Garden"
    ],
    "latitude": 18.516967,
    "longitude": 73.843899
  },
  {
    "id": 94,
    "name": "Sadashiv Peth Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Sadashiv Peth Residency B",
    "bhkType": "1 BHK",
    "city": "Pune",
    "locality": "Sadashiv Peth",
    "builtUpArea": "1349 sqft",
    "expectedPrice": 19130,
    "availableFrom": "2025-11-01",
    "bathroom": 3,
    "balcony": 1,
    "availableAmenities": [
      "Security",
      "Garden",
      "Lift"
    ],
    "latitude": 18.533033,
    "longitude": 73.930948
  },
  {
    "id": 95,
    "name": "Karve Nagar Property Owner",
    "postedBy": "Owner",
    "propertyType": "Apartment",
    "propertyAdsType": "Sell",
    "apartmentName": "Karve Nagar Residency A",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Karve Nagar",
    "builtUpArea": "1264 sqft",
    "expectedPrice": 11102737,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 1,
    "availableAmenities": [
      "Garden",
      "Lift",
      "Club House"
    ],
    "latitude": 18.489322,
    "longitude": 73.787034
  },
  {
    "id": 96,
    "name": "Karve Nagar Property Broker",
    "postedBy": "Broker",
    "propertyType": "Apartment",
    "propertyAdsType": "Rent",
    "apartmentName": "Karve Nagar Residency B",
    "bhkType": "3 BHK",
    "city": "Pune",
    "locality": "Karve Nagar",
    "builtUpArea": "1312 sqft",
    "expectedPrice": 18890,
    "availableFrom": "2025-11-01",
    "bathroom": 2,
    "balcony": 2,
    "availableAmenities": [
      "Play Area",
      "Lift",
      "Club House"
    ],
    "latitude": 18.567418,
    "longitude": 73.854154
  }
];